version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
      - image: circleci/mongo:4.2.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@6.9.0
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run: 
          name: install-dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}
    
      - run: 
          name: test-script
          command: npm test
      
      - run:
          name: code-coverage
          command: ./node_modules/.bin/nyc report --reporter=text-lcov
